name: odev_projesi
description: "Araç Kiralama - Desktop ve Mobile Flutter Uygulaması"
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mssql_connection: ^2.0.2
  intl: ^0.19.0
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true